// @generated by sunspec-gen. DO NOT EDIT.

//! Inverter (Single Phase)
/// Type alias for [`InverterSinglePhase`].
pub type Model101 = InverterSinglePhase;
/// Inverter (Single Phase)
///
/// Include this model for single phase inverter monitoring
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct InverterSinglePhase {
    /// Amps
    ///
    /// AC Current
    pub a: u16,
    /// Amps PhaseA
    ///
    /// Phase A Current
    ///
    /// Detail: Connected Phase
    pub a_ph_a: u16,
    /// Amps PhaseB
    ///
    /// Phase B Current
    pub a_ph_b: Option<u16>,
    /// Amps PhaseC
    ///
    /// Phase C Current
    pub a_ph_c: Option<u16>,
    #[allow(missing_docs)]
    pub a_sf: i16,
    /// Phase Voltage AB
    ///
    /// Phase Voltage AB
    pub pp_v_ph_ab: Option<u16>,
    /// Phase Voltage BC
    ///
    /// Phase Voltage BC
    pub pp_v_ph_bc: Option<u16>,
    /// Phase Voltage CA
    ///
    /// Phase Voltage CA
    pub pp_v_ph_ca: Option<u16>,
    /// Phase Voltage AN
    ///
    /// Phase Voltage AN
    pub ph_v_ph_a: u16,
    /// Phase Voltage BN
    ///
    /// Phase Voltage BN
    pub ph_v_ph_b: Option<u16>,
    /// Phase Voltage CN
    ///
    /// Phase Voltage CN
    pub ph_v_ph_c: Option<u16>,
    #[allow(missing_docs)]
    pub v_sf: i16,
    /// Watts
    ///
    /// AC Power
    pub w: i16,
    #[allow(missing_docs)]
    pub w_sf: i16,
    /// Hz
    ///
    /// Line Frequency
    pub hz: u16,
    #[allow(missing_docs)]
    pub hz_sf: i16,
    /// VA
    ///
    /// AC Apparent Power
    pub va: Option<i16>,
    #[allow(missing_docs)]
    pub va_sf: Option<i16>,
    /// VAr
    ///
    /// AC Reactive Power
    pub var: Option<i16>,
    #[allow(missing_docs)]
    pub var_sf: Option<i16>,
    /// PF
    ///
    /// AC Power Factor
    pub pf: Option<i16>,
    #[allow(missing_docs)]
    pub pf_sf: Option<i16>,
    /// WattHours
    ///
    /// AC Energy
    pub wh: u32,
    #[allow(missing_docs)]
    pub wh_sf: i16,
    /// DC Amps
    ///
    /// DC Current
    pub dc_a: Option<u16>,
    #[allow(missing_docs)]
    pub dc_a_sf: Option<i16>,
    /// DC Voltage
    ///
    /// DC Voltage
    pub dc_v: Option<u16>,
    #[allow(missing_docs)]
    pub dc_v_sf: Option<i16>,
    /// DC Watts
    ///
    /// DC Power
    pub dc_w: Option<i16>,
    #[allow(missing_docs)]
    pub dc_w_sf: Option<i16>,
    /// Cabinet Temperature
    ///
    /// Cabinet Temperature
    pub tmp_cab: i16,
    /// Heat Sink Temperature
    ///
    /// Heat Sink Temperature
    pub tmp_snk: Option<i16>,
    /// Transformer Temperature
    ///
    /// Transformer Temperature
    pub tmp_trns: Option<i16>,
    /// Other Temperature
    ///
    /// Other Temperature
    pub tmp_ot: Option<i16>,
    #[allow(missing_docs)]
    pub tmp_sf: i16,
    /// Operating State
    ///
    /// Operating state
    pub st: St,
    /// Vendor Operating State
    ///
    /// Vendor specific operating state code
    pub st_vnd: Option<u16>,
    /// Event1
    ///
    /// Event fields
    pub evt1: Evt1,
    /// Event Bitfield 2
    ///
    /// Reserved for future use
    pub evt2: Evt2,
    /// Vendor Event Bitfield 1
    ///
    /// Vendor defined events
    pub evt_vnd1: Option<EvtVnd1>,
    /// Vendor Event Bitfield 2
    ///
    /// Vendor defined events
    pub evt_vnd2: Option<EvtVnd2>,
    /// Vendor Event Bitfield 3
    ///
    /// Vendor defined events
    pub evt_vnd3: Option<EvtVnd3>,
    /// Vendor Event Bitfield 4
    ///
    /// Vendor defined events
    pub evt_vnd4: Option<EvtVnd4>,
}
#[allow(missing_docs)]
impl InverterSinglePhase {
    pub const A: crate::Point<Self, u16> = crate::Point::new(0, 1);
    pub const A_PH_A: crate::Point<Self, u16> = crate::Point::new(1, 1);
    pub const A_PH_B: crate::Point<Self, Option<u16>> = crate::Point::new(2, 1);
    pub const A_PH_C: crate::Point<Self, Option<u16>> = crate::Point::new(3, 1);
    pub const A_SF: crate::Point<Self, i16> = crate::Point::new(4, 1);
    pub const PP_V_PH_AB: crate::Point<Self, Option<u16>> = crate::Point::new(5, 1);
    pub const PP_V_PH_BC: crate::Point<Self, Option<u16>> = crate::Point::new(6, 1);
    pub const PP_V_PH_CA: crate::Point<Self, Option<u16>> = crate::Point::new(7, 1);
    pub const PH_V_PH_A: crate::Point<Self, u16> = crate::Point::new(8, 1);
    pub const PH_V_PH_B: crate::Point<Self, Option<u16>> = crate::Point::new(9, 1);
    pub const PH_V_PH_C: crate::Point<Self, Option<u16>> = crate::Point::new(10, 1);
    pub const V_SF: crate::Point<Self, i16> = crate::Point::new(11, 1);
    pub const W: crate::Point<Self, i16> = crate::Point::new(12, 1);
    pub const W_SF: crate::Point<Self, i16> = crate::Point::new(13, 1);
    pub const HZ: crate::Point<Self, u16> = crate::Point::new(14, 1);
    pub const HZ_SF: crate::Point<Self, i16> = crate::Point::new(15, 1);
    pub const VA: crate::Point<Self, Option<i16>> = crate::Point::new(16, 1);
    pub const VA_SF: crate::Point<Self, Option<i16>> = crate::Point::new(17, 1);
    pub const VAR: crate::Point<Self, Option<i16>> = crate::Point::new(18, 1);
    pub const VAR_SF: crate::Point<Self, Option<i16>> = crate::Point::new(19, 1);
    pub const PF: crate::Point<Self, Option<i16>> = crate::Point::new(20, 1);
    pub const PF_SF: crate::Point<Self, Option<i16>> = crate::Point::new(21, 1);
    pub const WH: crate::Point<Self, u32> = crate::Point::new(22, 2);
    pub const WH_SF: crate::Point<Self, i16> = crate::Point::new(24, 1);
    pub const DC_A: crate::Point<Self, Option<u16>> = crate::Point::new(25, 1);
    pub const DC_A_SF: crate::Point<Self, Option<i16>> = crate::Point::new(26, 1);
    pub const DC_V: crate::Point<Self, Option<u16>> = crate::Point::new(27, 1);
    pub const DC_V_SF: crate::Point<Self, Option<i16>> = crate::Point::new(28, 1);
    pub const DC_W: crate::Point<Self, Option<i16>> = crate::Point::new(29, 1);
    pub const DC_W_SF: crate::Point<Self, Option<i16>> = crate::Point::new(30, 1);
    pub const TMP_CAB: crate::Point<Self, i16> = crate::Point::new(31, 1);
    pub const TMP_SNK: crate::Point<Self, Option<i16>> = crate::Point::new(32, 1);
    pub const TMP_TRNS: crate::Point<Self, Option<i16>> = crate::Point::new(33, 1);
    pub const TMP_OT: crate::Point<Self, Option<i16>> = crate::Point::new(34, 1);
    pub const TMP_SF: crate::Point<Self, i16> = crate::Point::new(35, 1);
    pub const ST: crate::Point<Self, St> = crate::Point::new(36, 1);
    pub const ST_VND: crate::Point<Self, Option<u16>> = crate::Point::new(37, 1);
    pub const EVT1: crate::Point<Self, Evt1> = crate::Point::new(38, 2);
    pub const EVT2: crate::Point<Self, Evt2> = crate::Point::new(40, 2);
    pub const EVT_VND1: crate::Point<Self, Option<EvtVnd1>> = crate::Point::new(42, 2);
    pub const EVT_VND2: crate::Point<Self, Option<EvtVnd2>> = crate::Point::new(44, 2);
    pub const EVT_VND3: crate::Point<Self, Option<EvtVnd3>> = crate::Point::new(46, 2);
    pub const EVT_VND4: crate::Point<Self, Option<EvtVnd4>> = crate::Point::new(48, 2);
}
impl crate::sealed::Sealed for InverterSinglePhase {}
impl crate::Group for InverterSinglePhase {
    const LEN: u16 = 50;
}
impl InverterSinglePhase {
    fn parse_group(data: &[u16]) -> Result<(&[u16], Self), crate::ParseError> {
        let nested_data = data.get(50..).unwrap_or(&[]);
        Ok((
            nested_data,
            Self {
                a: Self::A.from_data(data)?,
                a_ph_a: Self::A_PH_A.from_data(data)?,
                a_ph_b: Self::A_PH_B.from_data(data)?,
                a_ph_c: Self::A_PH_C.from_data(data)?,
                a_sf: Self::A_SF.from_data(data)?,
                pp_v_ph_ab: Self::PP_V_PH_AB.from_data(data)?,
                pp_v_ph_bc: Self::PP_V_PH_BC.from_data(data)?,
                pp_v_ph_ca: Self::PP_V_PH_CA.from_data(data)?,
                ph_v_ph_a: Self::PH_V_PH_A.from_data(data)?,
                ph_v_ph_b: Self::PH_V_PH_B.from_data(data)?,
                ph_v_ph_c: Self::PH_V_PH_C.from_data(data)?,
                v_sf: Self::V_SF.from_data(data)?,
                w: Self::W.from_data(data)?,
                w_sf: Self::W_SF.from_data(data)?,
                hz: Self::HZ.from_data(data)?,
                hz_sf: Self::HZ_SF.from_data(data)?,
                va: Self::VA.from_data(data)?,
                va_sf: Self::VA_SF.from_data(data)?,
                var: Self::VAR.from_data(data)?,
                var_sf: Self::VAR_SF.from_data(data)?,
                pf: Self::PF.from_data(data)?,
                pf_sf: Self::PF_SF.from_data(data)?,
                wh: Self::WH.from_data(data)?,
                wh_sf: Self::WH_SF.from_data(data)?,
                dc_a: Self::DC_A.from_data(data)?,
                dc_a_sf: Self::DC_A_SF.from_data(data)?,
                dc_v: Self::DC_V.from_data(data)?,
                dc_v_sf: Self::DC_V_SF.from_data(data)?,
                dc_w: Self::DC_W.from_data(data)?,
                dc_w_sf: Self::DC_W_SF.from_data(data)?,
                tmp_cab: Self::TMP_CAB.from_data(data)?,
                tmp_snk: Self::TMP_SNK.from_data(data)?,
                tmp_trns: Self::TMP_TRNS.from_data(data)?,
                tmp_ot: Self::TMP_OT.from_data(data)?,
                tmp_sf: Self::TMP_SF.from_data(data)?,
                st: Self::ST.from_data(data)?,
                st_vnd: Self::ST_VND.from_data(data)?,
                evt1: Self::EVT1.from_data(data)?,
                evt2: Self::EVT2.from_data(data)?,
                evt_vnd1: Self::EVT_VND1.from_data(data)?,
                evt_vnd2: Self::EVT_VND2.from_data(data)?,
                evt_vnd3: Self::EVT_VND3.from_data(data)?,
                evt_vnd4: Self::EVT_VND4.from_data(data)?,
            },
        ))
    }
}
/// Operating State
///
/// Operating state
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub enum St {
    #[allow(missing_docs)]
    Off,
    #[allow(missing_docs)]
    Sleeping,
    #[allow(missing_docs)]
    Starting,
    #[allow(missing_docs)]
    Mppt,
    #[allow(missing_docs)]
    Throttled,
    #[allow(missing_docs)]
    ShuttingDown,
    #[allow(missing_docs)]
    Fault,
    #[allow(missing_docs)]
    Standby,
    /// Raw enum value not defined by the SunSpec model.
    Invalid(u16),
}
impl crate::sealed::Sealed for St {}
impl crate::EnumValue for St {
    type Repr = u16;
    const INVALID: Self::Repr = 65535;
    fn from_repr(value: Self::Repr) -> Self {
        match value {
            1 => Self::Off,
            2 => Self::Sleeping,
            3 => Self::Starting,
            4 => Self::Mppt,
            5 => Self::Throttled,
            6 => Self::ShuttingDown,
            7 => Self::Fault,
            8 => Self::Standby,
            value => Self::Invalid(value),
        }
    }
    fn to_repr(self) -> Self::Repr {
        match self {
            Self::Off => 1,
            Self::Sleeping => 2,
            Self::Starting => 3,
            Self::Mppt => 4,
            Self::Throttled => 5,
            Self::ShuttingDown => 6,
            Self::Fault => 7,
            Self::Standby => 8,
            Self::Invalid(value) => value,
        }
    }
}
impl crate::FixedSize for St {
    const SIZE: u16 = 1u16;
    const INVALID: Self = Self::Invalid(65535);
    fn is_invalid(&self) -> bool {
        matches!(self, Self::Invalid(_))
    }
}
bitflags::bitflags! {
    /// Event1
    ///
    /// Event fields
    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    #[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
    pub struct Evt1: u32 {
        #[allow(missing_docs)]
        const GroundFault = 1;
        #[allow(missing_docs)]
        const DcOverVolt = 2;
        #[allow(missing_docs)]
        const AcDisconnect = 4;
        #[allow(missing_docs)]
        const DcDisconnect = 8;
        #[allow(missing_docs)]
        const GridDisconnect = 16;
        #[allow(missing_docs)]
        const CabinetOpen = 32;
        #[allow(missing_docs)]
        const ManualShutdown = 64;
        #[allow(missing_docs)]
        const OverTemp = 128;
        #[allow(missing_docs)]
        const OverFrequency = 256;
        #[allow(missing_docs)]
        const UnderFrequency = 512;
        #[allow(missing_docs)]
        const AcOverVolt = 1024;
        #[allow(missing_docs)]
        const AcUnderVolt = 2048;
        #[allow(missing_docs)]
        const BlownStringFuse = 4096;
        #[allow(missing_docs)]
        const UnderTemp = 8192;
        #[allow(missing_docs)]
        const MemoryLoss = 16384;
        #[allow(missing_docs)]
        const HwTestFailure = 32768;
    }
}
impl crate::sealed::Sealed for Evt1 {}
impl crate::Value for Evt1 {
    fn decode(data: &[u16]) -> Result<Self, crate::DecodeError> {
        let value = u32::decode(data)?;
        Ok(Self::from_bits_retain(value))
    }
    fn encode(self) -> Box<[u16]> {
        self.bits().encode()
    }
}
impl crate::FixedSize for Evt1 {
    const SIZE: u16 = 2u16;
    const INVALID: Self = Self::from_bits_retain(4294967295u32);
    fn is_invalid(&self) -> bool {
        self.bits() == 4294967295u32
    }
}
bitflags::bitflags! {
    /// Event Bitfield 2
    ///
    /// Reserved for future use
    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    #[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
    pub struct Evt2: u32 {
    }
}
impl crate::sealed::Sealed for Evt2 {}
impl crate::Value for Evt2 {
    fn decode(data: &[u16]) -> Result<Self, crate::DecodeError> {
        let value = u32::decode(data)?;
        Ok(Self::from_bits_retain(value))
    }
    fn encode(self) -> Box<[u16]> {
        self.bits().encode()
    }
}
impl crate::FixedSize for Evt2 {
    const SIZE: u16 = 2u16;
    const INVALID: Self = Self::from_bits_retain(4294967295u32);
    fn is_invalid(&self) -> bool {
        self.bits() == 4294967295u32
    }
}
bitflags::bitflags! {
    /// Vendor Event Bitfield 1
    ///
    /// Vendor defined events
    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    #[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
    pub struct EvtVnd1: u32 {
    }
}
impl crate::sealed::Sealed for EvtVnd1 {}
impl crate::Value for EvtVnd1 {
    fn decode(data: &[u16]) -> Result<Self, crate::DecodeError> {
        let value = u32::decode(data)?;
        Ok(Self::from_bits_retain(value))
    }
    fn encode(self) -> Box<[u16]> {
        self.bits().encode()
    }
}
impl crate::FixedSize for EvtVnd1 {
    const SIZE: u16 = 2u16;
    const INVALID: Self = Self::from_bits_retain(4294967295u32);
    fn is_invalid(&self) -> bool {
        self.bits() == 4294967295u32
    }
}
bitflags::bitflags! {
    /// Vendor Event Bitfield 2
    ///
    /// Vendor defined events
    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    #[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
    pub struct EvtVnd2: u32 {
    }
}
impl crate::sealed::Sealed for EvtVnd2 {}
impl crate::Value for EvtVnd2 {
    fn decode(data: &[u16]) -> Result<Self, crate::DecodeError> {
        let value = u32::decode(data)?;
        Ok(Self::from_bits_retain(value))
    }
    fn encode(self) -> Box<[u16]> {
        self.bits().encode()
    }
}
impl crate::FixedSize for EvtVnd2 {
    const SIZE: u16 = 2u16;
    const INVALID: Self = Self::from_bits_retain(4294967295u32);
    fn is_invalid(&self) -> bool {
        self.bits() == 4294967295u32
    }
}
bitflags::bitflags! {
    /// Vendor Event Bitfield 3
    ///
    /// Vendor defined events
    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    #[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
    pub struct EvtVnd3: u32 {
    }
}
impl crate::sealed::Sealed for EvtVnd3 {}
impl crate::Value for EvtVnd3 {
    fn decode(data: &[u16]) -> Result<Self, crate::DecodeError> {
        let value = u32::decode(data)?;
        Ok(Self::from_bits_retain(value))
    }
    fn encode(self) -> Box<[u16]> {
        self.bits().encode()
    }
}
impl crate::FixedSize for EvtVnd3 {
    const SIZE: u16 = 2u16;
    const INVALID: Self = Self::from_bits_retain(4294967295u32);
    fn is_invalid(&self) -> bool {
        self.bits() == 4294967295u32
    }
}
bitflags::bitflags! {
    /// Vendor Event Bitfield 4
    ///
    /// Vendor defined events
    #[derive(Copy, Clone, Debug, Eq, PartialEq)]
    #[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
    pub struct EvtVnd4: u32 {
    }
}
impl crate::sealed::Sealed for EvtVnd4 {}
impl crate::Value for EvtVnd4 {
    fn decode(data: &[u16]) -> Result<Self, crate::DecodeError> {
        let value = u32::decode(data)?;
        Ok(Self::from_bits_retain(value))
    }
    fn encode(self) -> Box<[u16]> {
        self.bits().encode()
    }
}
impl crate::FixedSize for EvtVnd4 {
    const SIZE: u16 = 2u16;
    const INVALID: Self = Self::from_bits_retain(4294967295u32);
    fn is_invalid(&self) -> bool {
        self.bits() == 4294967295u32
    }
}
impl From<InverterSinglePhase> for crate::AnyModel {
    fn from(model: InverterSinglePhase) -> Self {
        Self::M101(model)
    }
}
impl crate::Model for InverterSinglePhase {
    const ID: u16 = 101;
    const NAME: &'static str = "inverter_single_phase";
    const LABEL: &'static str = "Inverter (Single Phase)";
    fn parse(data: &[u16]) -> Result<Self, crate::ParseError> {
        let (_, model) = Self::parse_group(data)?;
        Ok(model)
    }
}
