name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update nightly
      - run: rustup update 1.76 && rustup default 1.76
      - run: cargo +nightly update -Z minimal-versions
      - run: cargo check --all-features

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --all-features --workspace
    - name: Run tests
      run: cargo test --verbose --all-features
